### ISSUE TITLE
不会用

### ISSUE THREAD

**Issue by xingjian-zhang** [epigone707/LeagueSumTimer#1]
你好，你的项目很棒！
请问怎么安装？
可以让我英雄联盟打上王者吗？
🚀

**Comment by epigone707** [comment]
你好！

目前我们的应用还在审核阶段，等拳头riot给予许可后，我们就会发布release版本，用通俗的话讲，就是可以直接点击使用的那种！

对于你的第二问题，我的回答是可以的！我目前在美服是单排钻一，我的游戏理解和经验认为，这款应用确实能给玩家提供便利的协助！

谢谢！

707FlashTimer开发团队

**Comment by xingjian-zhang** [comment]
好的，谢谢！

我单排上王者就指望你这个项目了！

🫡

**Comment by xingjian-zhang** [comment]
补充一下，我现在是青铜段位，🙏

**Comment by YMY1666527646** [comment]
Is fist officially recognized?, Is it safe to use it and will the account be blocked?

**Comment by epigone707** [comment]
> Is fist officially recognized?, Is it safe to use it and will the account be blocked?

I registered it on https://developer.riotgames.com/ and it was officially approved by Riot recently. **It is safe to use**, but I haven't done the in-game testing yet cuz I'm busy recently. I will publish the release as soon as I finished it.
