### ISSUE TITLE
兼容linux终端

### ISSUE THREAD

**Issue by xenshinu** [epigone707/LeagueSumTimer#2]
你好，我一般在terminal里面打lol，请问有没有计划中的无GUI版本的开发？

**Comment by epigone707** [comment]
您好，

不好意思，由于业务繁忙，我们团队暂时没有这个开发计划。之后我们会在github上开通赞助sponsor通道，如果您有兴趣的话，可以众筹一个无GUI版本，赞助达到30RMB我们就会启动无GUI项目。

谢谢！

707FlashTimer开发团队
